### ISSUE TITLE
Allowed Machine Address fails when more than 1 NIC present

### ISSUE THREAD

**Issue by infamousjoeg** [infamousjoeg/aam-ccp-harden#3]
![image](https://user-images.githubusercontent.com/1924063/139451187-f2289722-d4f0-4ac5-8e6b-7f0265fb9e64.png)

**Comment by bab29** [comment]
Hopefully this is helpful for this section. 

`(Get-NetIPAddress -AddressState Preferred -AddressFamily IPv4).IPAddress`

https://github.com/infamousjoeg/aam-ccp-harden/blob/f224a258124d90675b82a4b7bf570bf1f76f8f8f/aam-ccp-harden.ps1#L139-L142
